setTimeout(()=>{
    document.getElementById("delta").innerHTML=10;
    setTimeout(()=>{
    document.getElementById("delta").innerHTML=9;
    setTimeout(()=>{
    document.getElementById("delta").innerHTML=8;
    setTimeout(()=>{
   document.getElementById("delta").innerHTML=7;
    setTimeout(()=>{
    document.getElementById("delta").innerHTML=6;
    setTimeout(()=>{
   document.getElementById("delta").innerHTML=5;
    setTimeout(()=>{
    document.getElementById("delta").innerHTML=4;
    setTimeout(()=>{
    document.getElementById("delta").innerHTML=3;
    setTimeout(()=>{
    document.getElementById("delta").innerHTML=2;
    setTimeout(()=>{
    document.getElementById("delta").innerHTML=1;
    setTimeout(()=>{
    document.getElementById("delta").innerHTML="Happy Independence Day";
    
  },1000)
  },1000)
  },1000)
  },1000)
  },1000)
  },1000)
  },1000)
  },1000)
  },1000)
  },1000)
  },1000)